version: "3.7"
services:
  proxy:
    image: nginx:1.14.2-alpine
    container_name: proxy
    ports:
      - "80:80"
    environment:
      DEFAULT_HOST: ${DOMAIN}
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      red:
        ipv4_address: 10.5.0.1
  frontend:
    image: node:16-buster-slim
    container_name: dev-front-app
    restart: always
    command: yarn run start
    volumes: 
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app  
    environment:
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL} 
    ports:
      - "3000:3000"
    networks:
      red: 
        ipv4_address: 10.5.0.2
  api:
    image: node:16-buster-slim
    container_name: dev-back-app
    restart: always
    command: yarn start
    volumes:
      - ./server:/usr/src/app
    working_dir: /usr/src/app
    environment:
      PORT: ${PORT}
      # VIRTUAL_HOST: ${DOMAIN}
    ports:
      - "4000:4000"
    networks:
      red: 
        ipv4_address: 10.5.0.3
    depends_on:
      - frontend
networks:
  red:
    name: red
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/8